apiVersion: "clickhouse.altinity.com/v1"
kind: "ClickHouseInstallation"
metadata:
  name: "storage"
spec:
  configuration:
    clusters:
      - name: "cluster"
        layout:
          shardsCount: 1